### ISSUE TITLE
Work Request for DevOps Strategy

### ISSUE THREAD

**Issue by Camkiki** [PhoenixTestOps/RestaurantMenuDesign#2]
Design and Visual for DevOps on Electronic Restaurant Menu Project Release One
Open Source Tools Requirement
Cloud Requirement

**Comment by Duduosun** [comment]
Request for Third Party DevOps Engineer

**Comment by Camkiki** [comment]
DevOps Engineer requested
Initiated conversation with DevOps Engineer
